# -*- mode: ruby -*-
# vi: set ft=ruby :

krnlver=ENV['KRNLVER']
ovsver=ENV['OVSVER']

if krnlver.nil? or ovsver.nil? then
  abort "need KRNLVER and OVSVER environment variables"
end

Vagrant.configure("2") do |config|

  config.vm.box = "stretch-" + krnlver
  config.vm.box_url = "file://../boxes/stretch-" + krnlver + ".box"
  config.vm.hostname = "cppofc"

  config.vm.synced_folder "../packages", "/vagrant_packages"
  config.vm.provision "shell" do |s|
    s.name = "provision cppofc develop ..."
    s.inline = <<-SHELL
      #sed -r -i 's_//[0-9.:]+/_//_g' /etc/apt/sources.list
      apt-get update
      apt-get -y upgrade
      apt-get -y install git python-six python-pip python2.7 openssl libatomic1 uuid-runtime less tcpdump libcap-ng-dev net-tools
      apt-get -y install lxde
      dpkg -i /vagrant_packages/openvswitch-datapath-module-KRNLVER-custom_OVSVER-1_amd64.deb
      dpkg -i /vagrant_packages/openvswitch-common_OVSVER-1_amd64.deb
      dpkg -i /vagrant_packages/openvswitch-switch_OVSVER-1_amd64.deb
      dpkg -i /vagrant_packages/python-openvswitch_OVSVER-1_all.deb
      #apt-get -y install tshark
      apt-get -y install build-essential libssl-dev 
      #apt-get -y install lxde
      wget https://dl.bintray.com/boostorg/release/1.64.0/source/boost_1_64_0.tar.gz
      pushd
      tar zxvf boost_1_64_0.tar.gz
      cd boost_1_64_0
      ./bootstrap.sh
      ./b2 threading=multi runtime-link=shared link=shared --layout=versioned variant=release install
      popd
      wget http://download.netbeans.org/netbeans/8.2/final/bundles/netbeans-8.2-cpp-linux-x64.sh
    SHELL
    s.inline = s.inline.gsub(/KRNLVER/,krnlver)
    s.inline = s.inline.gsub(/OVSVER/,ovsver)
  end

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    # vb.gui = true

    # Customize the amount of memory on the VM:
    vb.memory = "4096"
    vb.name = "cppofc"
    vb.cpus = 2

    vb.customize ["modifyvm", :id, "--nictype2", "virtio"]
#    vb.customize ["modifyvm", :id, "--nictype3", "virtio"]
#    vb.customize ["modifyvm", :id, "--nictype4", "virtio"]
#    vb.customize ["modifyvm", :id, "--nictype5", "virtio"]
    end

  config.vm.network :private_network, virtualbox__intnet: "mgmt",  ip: "192.168.10.22/24"
#  config.vm.network :private_network, virtualbox__intnet: "port1", ip: "192.168.30.30/24"
#  config.vm.network :private_network, virtualbox__intnet: "port2", ip: "192.168.40.30/24"
#  config.vm.network :private_network, virtualbox__intnet: "port3", ip: "192.168.50.30/24"
  #config.vm.network :public_network, bridge: "enp2s0", ip: "192.168.11.10/24"

end
