# -*- mode: ruby -*-
# vi: set ft=ruby :

krnlver=ENV['KRNLVER']
activeint=ENV['ACTIVEINT']

if krnlver.nil? or activeint.nil? then
  abort "need KRNLVER, ACTIVEINT environment variables"
end

Vagrant.configure("2") do |config|

  config.vm.box = "stretch-" + krnlver
  config.vm.box_url = "file://~/vagrant/boxes/stretch-" + krnlver + ".box"
  config.vm.hostname = "dnsmasq"

  config.vm.network :private_network, virtualbox__intnet: "mgmt", ip: "192.168.10.11/24"
  config.vm.network :public_network, bridge: "en", ip: "192.168.11.11/24"

  config.vm.provider "virtualbox" do |vb|

    vb.name = "dnsmasq"
    vb.memory = "512"
    vb.cpus = 1

    vb.customize ["modifyvm", :id, "--nictype2", "virtio"]
    vb.customize ["modifyvm", :id, "--nictype3", "virtio"]

    end

  #config.vm.synced_folder "../packages", "/vagrant_packages"

  config.vm.provision "shell" do |s|
    s.name = "provision dnsmasq ..."
    s.inline = <<-SHELL
      sed -i 's_http://ftp.us_http://192.168.10.10:3142/ftp.us_g' /etc/apt/sources.list
      apt-get update
      apt-get -y upgrade
      #apt-get -y install dnsmasq salt-minion
      apt-get -y install dnsmasq
      cat <<EOT >> /etc/dnsmasq.d/local
interface=ACTIVEINT
domain=example.net
pxe-service=x86PC, "Install Debian Stretch",pxelinux,192.168.11.11
enable-tftp=ACTIVEINT
tftp-root=/vagrant/tftp,ACTIVEINT
dhcp-fqdn
dhcp-client-update
dhcp-boot=pxelinux.0,pxeserver,192.168.11.11
dhcp-range=192.168.11.101,192.168.11.149,255.255.255.0,1h
log-queries=extra
#server=8.8.8.8
#server=8.8.4.4
host-record=salt,salt.example.net,192.168.11.21
dhcp-host=00:90:0b:40:a8:68,set:host_192.168.11.5,192.168.11.5,bnbx001,3600
dhcp-option=tag:host_192.168.11.5,option:netmask,255.255.255.0
# find by  dnsmasq --help dhcp
#dhcp-option=option:router,192.168.11.1
#dhcp-option=option:ntp-server,192.168.56.10
EOT
    systemctl restart dnsmasq
    #systemctl stop salt-minion
    #sed -i 's/vagrant/dnsmasq/' /etc/salt/minion_id
    #systemctl start salt-minion
    SHELL
    s.inline = s.inline.gsub(/ACTIVEINT/,activeint)
  end

end
