# -*- mode: ruby -*-
# vi: set ft=ruby :

# Build new kernel:
#
# OLDKRNLVER=4.8.7 NEWKRNLVER=4.8.12 vagrant up --provision-with bldkernel

Vagrant.configure("2") do |config|

  oldkrnlver=ENV['OLDKRNLVER']
  newkrnlver=ENV['NEWKRNLVER']

  if oldkrnlver.nil? or newkrnlver.nil? then 
    abort "need OLDKRNLVER, NEWKRNLVER environment variables"
  else
    puts "building kernel version #{newkrnlver} on #{oldkrnlver}"
  end;

  vmname="stretch-bld-" + newkrnlver
  config.vm.hostname = vmname

  config.vm.box = "stretch-" + oldkrnlver
  config.vm.box_url = "file://~/vagrant/boxes/stretch-" + oldkrnlver +".box"
  
  config.vm.synced_folder ".", "/vagrant", disabled: false
  config.vm.synced_folder "../packages", "/vagrant_packages", disabled: false

  # build new kernel and headers
  config.vm.provision "bldkernel", type: "shell" do |s|

    s.name = "bldkernel"
    s.inline = <<-SHELL
      sed -r -i 's_http://[^:/]+/_http://192.168.10.10:3142/_g' /etc/apt/sources.list
      bash /vagrant/buildkrnl.sh NEWKRNLVER
SHELL
    s.inline = s.inline.gsub(/NEWKRNLVER/,newkrnlver)
    puts s.inline
  end
  config.vm.provider "virtualbox" do |vb|
    vb.name = vmname
    vb.cpus = 2
    vb.customize ["modifyvm", :id, "--nictype2", "virtio"]
  end

  config.vm.network :private_network, virtualbox__intnet: "mgmt", ip: "192.168.10.31/24"

end

