# -*- mode: ruby -*-
# vi: set ft=ruby :

krnlver=ENV['KRNLVER']
ovsver=ENV['OVSVER']
consulver="0.8.1"

if krnlver.nil? or ovsver.nil? then
  abort "need KRNLVER and OVSVER environment variables"
end

Vagrant.configure("2") do |config|

  config.vm.box = "stretch-" + krnlver
  config.vm.box_url = "file://../boxes/stretch-" + krnlver + ".box"
  config.vm.hostname = "edge"

  config.vm.synced_folder "../packages", "/vagrant_packages"
  config.vm.provision "shell" do |s|
    s.name = "provision edge test ..."
    s.inline = <<-SHELL
      #sed -r -i 's_//[0-9.:]+/_//_g' /etc/apt/sources.list
      apt-get update
      apt-get -y upgrade
      apt-get -y install net-tools less tcpdump
      apt-get -y install python-six python2.7 openssl libatomic1 uuid-runtime less tcpdump libcap-ng-dev
      dpkg -i /vagrant_packages/openvswitch-datapath-module-KRNLVER-custom_OVSVER-1_amd64.deb
      dpkg -i /vagrant_packages/openvswitch-common_OVSVER-1_amd64.deb
      dpkg -i /vagrant_packages/openvswitch-switch_OVSVER-1_amd64.deb
      dpkg -i /vagrant_packages/python-openvswitch_OVSVER-1_all.deb
      apt-get -y install python-pip unzip
      wget -q https://releases.hashicorp.com/consul/CONSULVER/consul_CONSULVER_linux_amd64.zip
      unzip consul_CONSULVER_linux_amd64.zip
      mv consul /usr/local/sbin
      pip install monotonic
      pip install networkx
      pip install ryu
      sed -i -E '/^[ \t]+import eventlet$/ a eventlet.sleep()' /usr/local/lib/python2.7/dist-packages/ryu/lib/hub.py
      sed -i    's/^eventlet.sleep()$/    eventlet.sleep()/' /usr/local/lib/python2.7/dist-packages/ryu/lib/hub.py
      mkdir /var/log/ryu
      apt-get -y install git
#     apt-get -y install tshark
      git clone git://github.com/mininet/mininet
      mininet/util/install.sh -nf3
    SHELL
    s.inline = s.inline.gsub(/KRNLVER/,krnlver)
    s.inline = s.inline.gsub(/OVSVER/,ovsver)
    s.inline = s.inline.gsub(/CONSULVER/,consulver)
  end

# for the sed fixes above for eventlet:
#   https://github.com/eventlet/eventlet/issues/401

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    # vb.gui = true

    # Customize the amount of memory on the VM:
    #vb.memory = "1024"
    vb.name = "edgelab"
    vb.cpus = 1

    vb.customize ["modifyvm", :id, "--nictype2", "virtio"]
#    vb.customize ["modifyvm", :id, "--nictype3", "virtio"]
#    vb.customize ["modifyvm", :id, "--nictype4", "virtio"]
#    vb.customize ["modifyvm", :id, "--nictype5", "virtio"]
    end

  config.vm.network :private_network, virtualbox__intnet: "mgmt",  ip: "192.168.10.21/24"
#  config.vm.network :private_network, virtualbox__intnet: "port1", ip: "192.168.30.30/24"
#  config.vm.network :private_network, virtualbox__intnet: "port2", ip: "192.168.40.30/24"
#  config.vm.network :private_network, virtualbox__intnet: "port3", ip: "192.168.50.30/24"
  #config.vm.network :public_network, bridge: "enp2s0", ip: "192.168.11.10/24"

end
