# -*- mode: ruby -*-
# vi: set ft=ruby :

krnlver=ENV['KRNLVER']
ovsver=ENV['OVSVER']

if krnlver.nil? or ovsver.nil? then
  abort "need KRNLVER and OVSVER environment variables"
end

Vagrant.configure("2") do |config|

  config.vm.box = "stretch-" + krnlver
  config.vm.box_url = "file://../boxes/stretch-" + krnlver + ".box"
  config.vm.hostname = "edge"

  config.vm.synced_folder "../packages", "/vagrant_packages"
  config.vm.provision "shell" do |s|
    s.name = "provision edge test ..."
    s.inline = <<-SHELL
      #sed -r -i 's_//[0-9.:]+/_//_g' /etc/apt/sources.list
      apt-get update
      apt-get -y upgrade
      apt-get -y install python-six python2.7 openssl libatomic1 uuid-runtime less tcpdump libcap-ng-dev
      dpkg -i /vagrant_packages/openvswitch-datapath-module-KRNLVER-custom_OVSVER-1_amd64.deb
      dpkg -i /vagrant_packages/openvswitch-common_OVSVER-1_amd64.deb
      dpkg -i /vagrant_packages/openvswitch-switch_OVSVER-1_amd64.deb
      dpkg -i /vagrant_packages/python-openvswitch_OVSVER-1_all.deb
      apt-get -y install python-pip unzip
      wget -q https://releases.hashicorp.com/consul/0.7.2/consul_0.7.2_linux_amd64.zip
      unzip consul_0.7.2_linux_amd64.zip
      mv consul /usr/local/sbin
      pip install networkx
      pip install ryu
      mkdir /var/log/ryu
    SHELL
    s.inline = s.inline.gsub(/OVSVER/,ovsver)
  end

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    # vb.gui = true

    # Customize the amount of memory on the VM:
    #vb.memory = "1024"
    vb.name = "edgelab"
    vb.cpus = 1

    vb.customize ["modifyvm", :id, "--nictype2", "virtio"]
    vb.customize ["modifyvm", :id, "--nictype3", "virtio"]
    vb.customize ["modifyvm", :id, "--nictype4", "virtio"]
    vb.customize ["modifyvm", :id, "--nictype5", "virtio"]
    end

  config.vm.network :private_network, virtualbox__intnet: "mgmt",  ip: "192.168.10.21/24"
  config.vm.network :private_network, virtualbox__intnet: "port1", ip: "192.168.30.30/24"
  config.vm.network :private_network, virtualbox__intnet: "port2", ip: "192.168.40.30/24"
  config.vm.network :private_network, virtualbox__intnet: "port3", ip: "192.168.50.30/24"
  #config.vm.network :public_network, bridge: "enp2s0", ip: "192.168.11.10/24"

end
