# -*- mode: ruby -*-
# vi: set ft=ruby :

krnlver=ENV['KRNLVER']

if krnlver.nil? then
  abort "need KRNLVER environment variables"
end

Vagrant.configure("2") do |config|

  config.vm.box = "stretch-" + krnlver
  config.vm.box_url = "file://~/vagrant/boxes/stretch-" + krnlver + ".box"
  config.vm.hostname = "pprx"

  #config.vm.synced_folder "../packages", "/vagrant_packages"
  config.vm.provision "shell" do |s|
    s.name = "provision package proxy ..."
    s.inline = <<-SHELL
      sudo apt-get update
      sudo apt-get -y upgrade
      sudo apt-get -y install apt-cacher-ng
    SHELL
  end

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    # vb.gui = true

    # Customize the amount of memory on the VM:
    #vb.memory = "1024"
    vb.name = "pprx"
    vb.cpus = 1
    end

  config.vm.network :private_network, virtualbox__intnet: "mgmt", ip: "192.168.10.10/24"

end
