# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "stretch"
  config.vm.box_url = "file://~/vagrant/boxes/stretch.box"
  config.vm.hostname = "pprx"

  #config.vm.synced_folder "../packages", "/vagrant_packages"
  config.vm.provision "shell" do |s|
    s.name = "provision package proxy ..."
    s.inline = <<-SHELL
      sudo apt-get update
      sudo apt-get -y upgrade
      sudo apt-get -y install apt-cacher-ng
    SHELL
  end

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    # vb.gui = true

    # Customize the amount of memory on the VM:
    #vb.memory = "1024"
    vb.name = "pprx"
    vb.cpus = 1
    end

    config.vm.network "public_network"

end
